// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAsxgn8mTXQQ_0rYuz0IiqmcnytK6MOJk',
    appId: '1:418574862254:android:8adac146d18feeaed72a3f',
    messagingSenderId: '418574862254',
    projectId: 'flutter-first-app-7cd32',
    databaseURL: 'https://flutter-first-app-7cd32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-first-app-7cd32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9SXv4iIU5p4h3l7JAaIaPGYi0efbvv0',
    appId: '1:418574862254:ios:9807b7510d2b34a3d72a3f',
    messagingSenderId: '418574862254',
    projectId: 'flutter-first-app-7cd32',
    databaseURL: 'https://flutter-first-app-7cd32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-first-app-7cd32.appspot.com',
    iosClientId: '418574862254-q7mfv3pgrer4oioelfnu4od1char2ffg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG9SXv4iIU5p4h3l7JAaIaPGYi0efbvv0',
    appId: '1:418574862254:ios:9807b7510d2b34a3d72a3f',
    messagingSenderId: '418574862254',
    projectId: 'flutter-first-app-7cd32',
    databaseURL: 'https://flutter-first-app-7cd32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-first-app-7cd32.appspot.com',
    iosClientId: '418574862254-q7mfv3pgrer4oioelfnu4od1char2ffg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
